language: node_js
node_js:
- '7'
- '8'
before_script:
- npm install typescript -g
- npm install
script: npm test
deploy:
  provider: npm
  email: tastee.is.good@gmail.com
  api_key:
    secure: ORvbbALCJMC0LoydXYn4xFVrqGczxKYflQjeoP53FcPAnU5Kyk3PwIuXNYUjdW1JeibNbd5lhdAhtRuMFMjz1SiJdw0UVkoXahxfNPFz/EocUpps2MWKNc8IXfqLXN6rwSMQk/fmm2jLtgjafFri1LySIdNA9bzar2VSe0+Ikj6yV5LpnzZCJuKxrDaox/rWaPy0goRLDFD3IAqJfqLvAmfIAKBotNUdUgn4aJYrqGBla6UieO5c9XVQiBwXJDn/JyKpQuf2PQr6Oe17/Ppcy9+3cgTArmJULCKpgxf4gOJ33eonlbHpo3CV7FJ3RN/1F23y0UGZ1FLDuBuHhnI7c1MN7RZ/DYjwyd8+//5gyipYGCHzNg53im2bHA7YKE+wAqzFJmAlFiWpQMfUvwujrmrfjbRU2hpkQ8HiXIJ8QPol+9qqkXxc+ZaqaK3T92P38DaLIelzi/psYwwO3Ah7pBY0ATA9EMnYsT7ijkzWIeNJPA8bN7mV4iKt5TDcIX6JzVA5XrWZEjCtBl20uoU5nbGSh8ypGDDOewo1+WCM6CTXqDFgQ8V4+1VdjeuIKjpkaqoXyDiArmLL8+fjwcLz03dRwQlLFNO4OrmxZ1xPKTweN+d0YRUdn5V8c37N5rRtIWYMLapP5qZRUh+R7EFY5SLqYvMvtVC5KIdmots9Wi0=
  on:
    tags: true
    repo: tastee/tastee-html
